### ISSUE TITLE
create test for first 8 seconds vs last 2 second randomly genereated

### ISSUE THREAD

**Issue by godfreyhobbs** [ankitaverma/CS8803#2]

**Comment by godfreyhobbs** [comment]
take data
split 8 seconds 2 seconds
Generate random data with range for 2 seconds
Calculate the L2 error between random values for 2 seconds and actual final two seconds of data.

**Comment by godfreyhobbs** [comment]
The following is doing something similar:
https://gist.github.com/kylejmcintyre/0e7338571956479923ec
(from: https://piazza.com/class/i9dmgi38580428?cid=391)

**Comment by ankitaverma** [comment]
assigning it to Priyank

**Comment by TempleOwl** [comment]
author = 'ppatel'

def split(in_data):
    split80 = in_data[0:int(len(in_data)_0.8):1]
    split20 = in_data[int(len(in_data)_0.8):len(in_data):1]
    return split80, split20

def L2Error(actual_data, pred_data):
    predFrames = pred_data[0:60:1]
    actualFrames= actual_data[0:60:1]
    predX = []
    predY = []
    actualX = []
    actualY = []
    error = 0
    for i in range(len(predFrames)):
            predX.append(predFrames[i][0])
            predY.append(predFrames[i][1])
            actualX.append(actualFrames[i][0])
            actualY.append(actualFrames[i][1])
            error = error + (actualX[i] - predX[i])**2 + (actualY[i] - predY[i])**2
            error = sqrt(error)
    return predFrames, actualFrames, error

input_file = 'test01.txt'
input_array = get_input(input_file)

split80, split20 = split(input_array)
predFrames, actualFrames, error = L2Error(input_array, input_array)

print split80
print split20
print predFrames
print actualFrames
print error
